### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by cedar0817** [zhanglaplace/MobileFaceNet#14]
您好！为什么我训练到第三轮（300）的时候loss值就下降到1以下，请问是什么原因导致的？

**Comment by guojingsai** [comment]
> 您好！为什么我训练到第三轮（300）的时候loss值就下降到1以下，请问是什么原因导致的？

您好，请问你是在什么样的环境下跑这个工程的，cuda与nvidia版本能告知下吗，一直遇到Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version，请问这个问题你有遇到过吗？

**Comment by zhanglaplace** [comment]
@guojingsai @cedar0817 这个是好久前跑的了，cuda的问题就是你编译caffe的时候cuda和显卡适配的问题。

**Comment by guojingsai** [comment]
好的，了解，那你之前这个工程用的镜像还在吗？

**Comment by zhanglaplace** [comment]
@guojingsai 不在了，这个应该是2-3年前的工作了。而且目前github上有很多pytorch与mxnet的Repo。你可以试试

**Comment by guojingsai** [comment]
好的，感谢
