### ISSUE TITLE
请问你的normlize层是怎么实现的？

### ISSUE THREAD

**Issue by olojuwin** [zhanglaplace/MobileFaceNet#4]
normalize_layer

**Comment by ykk648** [comment]
+1

**Comment by zhanglaplace** [comment]
@olojuwin @cloisonne https://github.com/happynear/caffe-windows/blob/504d8a85f552e988fabff88b026f2c31cb778329/src/caffe/layers/normalize_layer.cpp

**Comment by ykk648** [comment]
已解决 谢谢
