### ISSUE TITLE
about the lfw accuracy

### ISSUE THREAD

**Issue by VivienFu** [zhanglaplace/MobileFaceNet#8]
I test the model you give out, the acc is lower than yours
1 group acc is 0.968333
2 group acc is 0.976667
3 group acc is 0.980000
4 group acc is 0.983333
5 group acc is 0.995000
6 group acc is 0.988333
7 group acc is 0.990000
8 group acc is 0.988333
9 group acc is 0.990000
10 group acc is 0.978333
the acc is 0.983833

The lfw aligned face images I used come form insightface project, origin image size is 112X112, I crop it to 112*96 by cut width.
 I also tried resize 112X112 to 112X96, the acc is 0.984000

is there any difference between my lfw and yours?

**Comment by zhanglaplace** [comment]
@VivienFu different align method may result in different test results.
you could test this:  https://pan.baidu.com/s/1lu1N-8vH5Lpx4K3UGYR4pA 提取码: 7445
If the result is the same as mine. Please tell me about it. Thanks 😸
